use `Pizzeria`;
DROP TABLE IF EXISTS pizza_topping;
DROP TABLE IF EXISTS topping;
DROP TABLE IF EXISTS pizza_discount;
DROP TABLE IF EXISTS pizza;
DROP TABLE IF EXISTS base_pizza;
DROP TABLE IF EXISTS commission_discount;
DROP TABLE IF EXISTS discount;
DROP TABLE IF EXISTS pickup_commission;
DROP TABLE IF EXISTS dinein_commission;
DROP TABLE IF EXISTS delivery_commission;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS commission;